### PR TITLE
Correct Typo

### PR DESCRIPTION
**Pull request by Dargmuesli**

### CODE REVIEW

**Comment by rcjsuen** [comment]
I won't merge this just yet until some stylistic things have been resolved but the code looks good.

**Comment by rcjsuen** [comment]
@Dargmuesli Apologies for the delay in getting back to you.

To keep things in the project consistent, please do the following by **amending** your commit and then **force pushing** to your branch.

1. Amend your commit message to include `Fix #47` in the beginning of the commit message.
1. When amending your commit, please also use `-s` so that we can get a `Signed-off-by` footer in the commit message.

Thank you again for your contribution! I look forward to merging this in!

**Comment by Dargmuesli** [comment]
Done :) I hope that's what you meant.

**Comment by rcjsuen** [comment]
@Dargmuesli Thank you for updating your pull request! I have merged it into `master`.

Have a wonderful week!

**Comment by Dargmuesli** [comment]
Thanks a lot, you too! :)

**Pull request merged**
